name: Testes

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pytest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Lab01
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Instalar dependências de teste
        run: pip install -r requirements-dev.txt

      - name: Rodar testes
        run: pytest tests -v
